### ISSUE TITLE
How to rename the heading "Articles"

### ISSUE THREAD

**Issue by PepsimanX** [cwchentw/lightweight-cms#17]
Hello, how to rename the heading "Articles" to "Статьи" ?

![Articles](https://user-images.githubusercontent.com/124836313/224389777-6b4cdd8d-cb1d-4694-826c-871c3c284d9d.png)

**Comment by cwchentw** [comment]
Hi there:

The text is in *layout/home.php*.

If you adopt our *default* theme, it is in https://github.com/cwchentw/lightweight-cms/blob/master/themes/default/layout/home.php .

In contrary, if you adopt our *multilingual* theme, it is a bit complex. The location of the text is in https://github.com/cwchentw/lightweight-cms/blob/master/themes/multilingual/layout/home.php . Nevertheless, the text is rendered according to the locale of a web page. The locale data is in https://github.com/cwchentw/lightweight-cms/tree/master/themes/multilingual/trans .

If you use your theme, you are on your own.

Hope this answers your question.

**Comment by PepsimanX** [comment]
> 
Does not work. Updated the page Ctrl + F5

![1](https://user-images.githubusercontent.com/124836313/224482595-cf6b66bd-ed5b-4596-b2e1-18c23556080c.png)
![2](https://user-images.githubusercontent.com/124836313/224482598-14ec2223-2d02-498a-b4f8-2803d86a5fde.png)
![3](https://user-images.githubusercontent.com/124836313/224482606-150f063d-c566-4e13-964c-e40506d62679.png)

**Comment by cwchentw** [comment]
LightweightCMS adopts *multilingual* theme by default.

Change the **SITE_THEME** to *default*. https://github.com/cwchentw/lightweight-cms/blob/master/config/information.template.php

Re-initialize your local clone:
```
$ ./tools/bin/init
```

Run the modified site again:
```
$ ./tools/bin/serve
```

We recommend our users copy one of our themes as your template instead of modifying it in-place.

**Comment by PepsimanX** [comment]
> 

Thank you.

**Comment by PepsimanX** [comment]
Why did the heading disappear?

![D](https://user-images.githubusercontent.com/124836313/224493942-c7867079-0d69-4d5c-b8d0-dc9fc90378ad.png)
![D21](https://user-images.githubusercontent.com/124836313/224493946-299053b7-ccdc-4ae4-bdcf-565cad76e75b.png)

**Comment by PepsimanX** [comment]
thanks a lot.
